#!/usr/bin/python3
import socket
import sys

def nc(hostname, port, content):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((hostname, port))
    s.sendall(content)
    s.shutdown(socket.SHUT_WR)
    s.close()

send = sys.argv[3] + "\r"
nc(sys.argv[1], int(sys.argv[2]), send.encode('utf-8'))

